react-figma/react-figma

- src/components/frame/__tests__/Frame.test.tsx
- src/components/frame/__tests__/__snapshots__/Frame.test.tsx.snap
Adds component tests for the `Frame` component.
The tests have also been modified to prepare component for assertions using `act()` 🎉  
Reference: https://reactjs.org/docs/test-renderer.html#testrendereract
Console error related to creating the component:
> test: Add frame tests

- src/components/frame/Frame.tsx
- src/components/rectangle/Rectangle.tsx
- src/components/rectangle/__tests__/__snapshots__/Rectangle.test.tsx.snap
- src/hooks/useFillsPreprocessor.ts
> Fix Rectangle fill bug

- examples/basic/src/App.tsx
- examples/basic/src/code.tsx
- examples/design-system/src/App.tsx
- src/components/component/Component.tsx
- src/components/frame/Frame.tsx
- src/components/page/Page.tsx
- src/components/rectangle/Rectangle.tsx
- src/components/text/Text.tsx
- src/hooks/useYogaLayout.tsx
- src/workers/yogaWorker.ts
- src/yogaHandler.ts
> Yoga refactor

- package.json
- src/__tests__/__snapshots__/renderer.test.tsx.snap
- src/__tests__/renderer.test.tsx
- yarn.lock
> Renderer test

- .circleci/config.yml
> Create CircleCI configuration

- examples/basic/src/App.tsx
- examples/basic/src/code.tsx
- package.json
- src/__tests__/__snapshots__/renderer.test.tsx.snap
- src/__tests__/renderer.test.tsx
- src/renderer.tsx
- src/renderers/text.ts
- yarn.lock
> Fix inserting new component between other components

- src/__tests__/__snapshots__/renderer.test.tsx.snap
- src/__tests__/renderer.test.tsx
- src/renderer.tsx
> Implement removing node at hydration

- Summary.md
- examples/groups/README.md
- examples/groups/src/App.tsx
Change colors at groups example. Close #95.
> Add readme to groups example

- examples/design-system/src/App.tsx
- examples/groups/src/App.tsx
- src/components/component/Component.tsx
- src/components/frame/Frame.tsx
- src/components/group/Group.tsx
- src/components/page/Page.tsx
- src/hooks/useYogaLayout.tsx
- src/index.ts
> Implement hiding YogaContextProvider inside

- examples/design-system/src/App.tsx
- examples/groups/src/App.tsx
- src/__tests__/__snapshots__/renderer.test.tsx.snap
- src/components/component/Component.tsx
- src/components/frame/Frame.tsx
- src/components/page/Page.tsx
- src/components/text/Text.tsx
- src/hooks/useYogaLayout.tsx
- src/index.ts
- src/renderer.tsx
- src/yoga.ts
- src/yogaStream.ts
> Exclude yoga context provider

- examples/view/README.md
- examples/view/manifest.json
- examples/view/package.json
- examples/view/src/App.tsx
- examples/view/src/code.tsx
- examples/view/src/ui.tsx
- examples/view/webpack.config.js
- src/components/view/View.tsx
- src/index.ts
> Create View component

- examples/design-system/src/App.tsx
- examples/groups/src/App.tsx
- src/__tests__/__snapshots__/renderer.test.tsx.snap
- src/__tests__/renderer.test.tsx
- src/components/page/Page.tsx
- src/renderer.tsx
> Implement isCurrent prop support at Page

- src/components/Image/Image.tsx
- src/components/Image/__tests__/Image.test.tsx
- src/components/Image/__tests__/__snapshots__/Image.test.tsx.snap
- src/helpers/size.ts
- src/styleTransformers/transformBorderProperties.ts
- src/styleTransformers/transformGeometryStyleProperties.ts
- src/styleTransformers/transformLayoutStyleProperties.ts
> implement image component #105

- examples/vector/src/App.tsx
- package-lock.json
- src/components/Image/Image.tsx
- src/components/component/Component.tsx
- src/components/ellipse/Ellipse.tsx
- src/components/frame/Frame.tsx
- src/components/frame/__tests__/__snapshots__/Frame.test.tsx.snap
- src/components/group/Group.tsx
- src/components/line/Line.tsx
- src/components/page/Page.tsx
- src/components/rectangle/Rectangle.tsx
- src/components/star/Star.tsx
- src/components/text/Text.tsx
- src/components/vector/Vector.tsx
- src/components/view/View.tsx
> refactor: 💡 replace React.ElementType with React.FC

- docs/styling.md
- examples/design-system/src/App.tsx
- src/components/Image/Image.tsx
- src/components/component/Component.tsx
- src/components/ellipse/Ellipse.tsx
- src/components/frame/Frame.tsx
- src/components/group/Group.tsx
- src/components/line/Line.tsx
- src/components/page/Page.tsx
- src/components/rectangle/Rectangle.tsx
- src/components/star/Star.tsx
- src/components/text/Text.tsx
- src/components/vector/Vector.tsx
- src/helpers/StyleSheet.ts
- src/index.ts
- src/types.ts
- src/workers/yogaWorker.ts
> Style sheet module

- src/__tests__/__snapshots__/renderer.test.tsx.snap
- src/__tests__/renderer.test.tsx
- src/components/text/Text.tsx
- src/renderer.tsx
- src/renderers/text.ts
> Text children

- src/styleTransformers/__tests__/transformDimension.ts
- src/styleTransformers/transformDimension.ts
- src/yoga/YogaStyleProperties.ts
- src/yoga/__tests__/__snapshots__/applyStyleToYogaNode.ts.snap
- src/yoga/__tests__/applyStyleToYogaNode.ts
- src/yoga/applyStyleToYogaNode.ts
- src/yoga/yogaSerializer.ts
> Percentage style values

- docs/styling.md
- examples/design-system/src/App.tsx
- src/yoga/YogaStyleProperties.ts
- src/yoga/__tests__/__snapshots__/applyStyleToYogaNode.ts.snap
- src/yoga/__tests__/applyStyleToYogaNode.ts
- src/yoga/applyStyleToYogaNode.ts
Closes #130, #131, #132, #133, #134
> New yoga style props

- docs/styling.md
- examples/basic/src/App.tsx
- src/helpers/color.ts
- src/styleTransformers/__tests__/transformBlendProperties.ts
- src/styleTransformers/transformBlendProperties.ts
> Implementing shadow style props

- src/helpers/Platform.ts
- src/helpers/__tests__/Platform.test.ts
- src/index.ts
> Create Platform module

- docs/styling.md
- examples/design-system/src/App.tsx
- src/styleTransformers/transformTextStyleProperties.ts
> Implementing fontSize text style prop support #162

- contributing.md
[Fixes #100](https://github.com/react-figma/react-figma/issues/100)
> Add webpack requirement to contributing docs

- examples/basic/src/code.tsx
- examples/design-system/src/code.tsx
- examples/dynamic-layout/src/code.tsx
- examples/ellipse/src/code.tsx
- examples/groups/src/code.tsx
- examples/line/src/code.tsx
- examples/star/src/code.tsx
- examples/svg/src/code.tsx
- examples/vector/src/App.tsx
- examples/vector/src/code.tsx
- examples/view/src/code.tsx
- package.json
- src/__tests__/__snapshots__/renderer.test.tsx.snap
- src/__tests__/renderer.test.tsx
- src/components/text/Text.tsx
- src/components/text/__tests__/__snapshots__/Text.test.tsx.snap
- src/components/vector/__tests__/Vector.test.tsx
- src/helpers/wait.ts
- src/hooks/useFontName.ts
- src/hooks/useTextChildren.ts
- src/renderer.tsx
- src/renderers/text.ts
- src/styleTransformers/transformGeometryStyleProperties.ts
- yarn.lock
> Fonts auto-loading

- docs/styling.md
- src/styleTransformers/__tests__/__snapshots__/transformTextStyleProperties.test.ts.snap
- src/styleTransformers/__tests__/transformDimension.ts
- src/styleTransformers/__tests__/transformTextStyleProperties.test.ts
- src/styleTransformers/transformDimension.ts
- src/styleTransformers/transformTextStyleProperties.ts
> textAlign, lineHeight support

- docs/styling.md
- src/styleTransformers/__tests__/__snapshots__/transformTextStyleProperties.test.ts.snap
- src/styleTransformers/__tests__/transformTextStyleProperties.test.ts
- src/styleTransformers/transformBlendProperties.ts
- src/styleTransformers/transformShadowToEffect.ts
- src/styleTransformers/transformTextStyleProperties.ts
Closes #165 
Closes #166 
Closes #167
> text shadow, textDecorationLine, letterSpacing support

- package.json
- src/styleTransformers/__tests__/__snapshots__/transformColors.ts.snap
- src/styleTransformers/__tests__/transformColors.ts
- src/styleTransformers/transformBlendProperties.ts
- src/styleTransformers/transformBorderProperties.ts
- src/styleTransformers/transformColors.ts
- src/styleTransformers/transformGeometryStyleProperties.ts
- src/styleTransformers/transformShadowToEffect.ts
- src/styleTransformers/transformTextStyleProperties.ts
- yarn.lock
> Different color formats support #151

- src/styleTransformers/__tests__/__snapshots__/transformTextStyleProperties.test.ts.snap
- src/styleTransformers/transformTextStyleProperties.ts
> Implementing lineHeight unitless compatibility #190

- src/__tests__/__snapshots__/renderer.test.tsx.snap
- src/__tests__/renderer.test.tsx
- src/components/svg/Svg.md
- src/helpers/hashCode.ts
- src/renderer.tsx
- src/renderers/svg.ts
> Svg dynamic source

- docs/styling.md
- package.json
- src/__tests__/renderer.test.tsx
- src/helpers/isEqualFontStyle.ts
- src/hooks/__tests__/useFontName.test.tsx
- src/hooks/useFontName.ts
- src/renderers/__tests__/text.test.ts
- src/renderers/text.ts
- src/styleTransformers/transformTextStyleProperties.ts
- yarn.lock
> #227 font weight 600

- src/styleTransformers/__tests__/__snapshots__/transformGeometryStyleProperties.test.ts.snap
- src/styleTransformers/__tests__/transformGeometryStyleProperties.test.ts
- src/styleTransformers/transformGeometryStyleProperties.ts
> Gradient background should be supported at the backgroundImage

- src/helpers/StyleSheet.md
- src/helpers/StyleSheet.ts
- src/helpers/__tests__/StyleSheet.test.ts
- src/helpers/__tests__/__snapshots__/StyleSheet.test.ts.snap
> #233 StyleSheet.compose

- package.json
- src/helpers/StyleSheet.ts
- src/helpers/__tests__/StyleSheet.test.ts
- src/helpers/__tests__/__snapshots__/StyleSheet.test.ts.snap
- yarn.lock
> Fix StyleSheet.compose should handle simple styles #240

- src/hooks/__tests__/useSelectionChange.test.tsx
- src/hooks/useSelectionChange.ts
> Cannot change element positions while plugin is running

- src/components/component/Component.tsx
- src/components/component/Instance.tsx
- src/components/frame/Frame.tsx
- src/mixins/autoLayoutMixin.ts
- src/renderers/__tests__/frame.test.ts
- src/renderers/component.ts
- src/renderers/frame.ts
- src/renderers/instance.ts
- src/types.ts
> Implementing Auto-Layout properties on FrameNode

- docs/colors.md
- docs/styling.md
- website/sidebars.json
> Documenting supported colors

- README.md
- docs/data-fetching.md
- examples/fetching/README.md
- examples/fetching/manifest.json
- examples/fetching/package.json
- examples/fetching/src/App.tsx
- examples/fetching/src/code.tsx
- examples/fetching/src/ui.tsx
- examples/fetching/tsconfig.json
- examples/fetching/webpack.config.js
- package.json
- src/hooks/useFetch.ts
- src/index.ts
- src/uiWorker.ts
- src/workers/fetchWorker.ts
- website/sidebars.json
- yarn.lock
> #119 data fetching

- docs/styling.md
- package.json
- src/yoga/YogaStyleProperties.ts
- src/yoga/__tests__/__snapshots__/applyStyleToYogaNode.test.ts.snap
- src/yoga/__tests__/applyStyleToYogaNode.test.ts
- src/yoga/applyStyleToYogaNode.ts
- yarn.lock
> Implementing overflow style prop support

- src/components/frame/Frame.tsx
- src/components/frame/__tests__/Frame.test.tsx
- src/components/frame/__tests__/__snapshots__/Frame.test.tsx.snap
- src/renderers/frame.ts
> Fix View with children don't supports border #254

- README.md
- docs/configure.md
- docs/data-fetching.md
- examples/basic/src/ui.tsx
- examples/design-system/src/ui.tsx
- examples/dynamic-layout/src/ui.tsx
- examples/fetching/src/ui.tsx
- examples/groups/src/ui.tsx
- examples/interactive/src/ui.tsx
- src/uiWorker.ts
> #256 optional fetch

- package.json
- src/__tests__/__snapshots__/renderer.test.tsx.snap
- src/helpers/removeNodeBatchId.ts
- src/workers/yogaWorker.ts
- src/yoga/__tests__/__snapshots__/integration.tsx.snap
- src/yoga/__tests__/integration.tsx
- yarn.lock
> Create integration yoga layout test

- examples/auto-layout/README.md
- examples/auto-layout/manifest.json
- examples/auto-layout/package.json
- examples/auto-layout/src/App.tsx
- examples/auto-layout/src/code.tsx
- examples/auto-layout/src/ui.tsx
- examples/auto-layout/tsconfig.json
- examples/auto-layout/webpack.config.js
- figma.d.ts
- src/mixins/__tests__/layoutMixin.test.ts
- src/mixins/layoutMixin.ts
- src/types.ts
Create auto-layout example.
Update figma.d.ts
> Implement layoutAlign prop support #270

- examples/auto-layout/src/App.tsx
- examples/auto-layout/src/ui.tsx
- src/components/Image/__tests__/__snapshots__/Image.test.tsx.snap
- src/components/ellipse/Ellipse.tsx
- src/components/ellipse/__tests__/__snapshots__/Ellipse.test.tsx.snap
- src/components/group/Group.tsx
- src/components/line/Line.tsx
- src/components/rectangle/Rectangle.tsx
- src/components/rectangle/__tests__/__snapshots__/Rectangle.test.tsx.snap
- src/components/star/Star.tsx
- src/components/star/__tests__/__snapshots__/Star.test.tsx.snap
- src/components/svg/Svg.tsx
- src/components/text/Text.tsx
- src/components/text/__tests__/__snapshots__/Text.test.tsx.snap
- src/components/vector/Vector.tsx
- src/components/vector/__tests__/__snapshots__/Vector.test.tsx.snap
- src/components/view/__tests__/View.test.tsx
- src/components/view/__tests__/__snapshots__/View.test.tsx.snap
- src/styleTransformers/transformAutoLayoutToYoga.ts
- src/yoga/yogaStream.ts
> Implement layoutAlign prop compatibility with Yoga

- src/styleTransformers/__tests__/__snapshots__/transformTextStyleProperties.test.ts.snap
- src/styleTransformers/__tests__/transformTextStyleProperties.test.ts
- src/styleTransformers/transformTextStyleProperties.ts
> Unitless lineHeight should be converted to pixels value

- src/components/frame/Frame.tsx
- src/mixins/frameSpecificMixin.ts
- src/renderers/frame.ts
- src/types.ts
> Implement layoutGrids on Frame component #294

- src/mixins/sceneNodeMixin.ts
- src/renderers/__tests__/frame.test.ts
- src/renderers/component.ts
- src/renderers/ellipse.ts
- src/renderers/frame.ts
- src/renderers/group.ts
- src/renderers/instance.ts
- src/renderers/line.ts
- src/renderers/rectangle.ts
- src/renderers/star.ts
- src/renderers/svg.ts
- src/renderers/text.ts
- src/renderers/vector.ts
- src/types.ts
> #299 scene node mixin

- docs/hmr.md
- examples/basic-hmr/README.md
- examples/basic-hmr/package.json
- examples/basic-hmr/ui.html
- examples/basic-hmr/webpack.config.js
- examples/basic-hmr/webpack.ui.config.js
- package.json
- website/sidebars.json
- yarn.lock
> #302 hmr improvement

- docs/api/Platform.md
Hello,
This tiny PR will fix : 
- 2 typos in `docs/api/Platform.md`
Bye! :robot:
> Fix typos in docs/api/Platform.md

- src/__tests__/__snapshots__/renderer.test.tsx.snap
- src/components/text/__tests__/__snapshots__/Text.test.tsx.snap
- src/components/view/__tests__/__snapshots__/View.test.tsx.snap
- src/styleTransformers/__tests__/__snapshots__/transformTextStyleProperties.test.ts.snap
- src/styleTransformers/transformTextStyleProperties.ts
> Set black color as default for text

- src/hooks/useYogaLayout.ts
- src/yoga/yogaStream.ts
Related to #334 
Related to #323
> Fix yoga calculation execution (concat -> exhaust)

- package.json
- src/styleTransformers/transformColors.ts
- yarn.lock
> Fix TypeError: parse is not a function

- README.md
- docs/api/Component.md
- examples/component-variants/README.md
- examples/component-variants/manifest.json
- examples/component-variants/package.json
- examples/component-variants/src/App.tsx
- examples/component-variants/src/code.tsx
- examples/component-variants/src/ui.tsx
- examples/component-variants/tsconfig.json
- examples/component-variants/webpack.config.js
- jsx-interfaces.d.ts
- src/__tests__/__snapshots__/renderer.test.tsx.snap
- src/components/component/ComponentSet.tsx
- src/components/component/Instance.tsx
- src/index.ts
- src/renderers/component.ts
- src/renderers/componentset.ts
- src/renderers/index.ts
- src/renderers/instance.ts
- src/rpc.ts
- yarn.lock
> Figma variants supporting

- docs/styling.md
- src/components/text/Text.tsx
- src/components/text/__tests__/Text.test.tsx
- src/components/text/__tests__/__snapshots__/Text.test.tsx.snap
- src/components/view/View.tsx
- src/components/view/__tests__/View.test.tsx
- src/components/view/__tests__/__snapshots__/View.test.tsx.snap
> Implement A text with display: block should get full width (width: 100%)

- docs/api/Dimensions.md
- docs/api/useWindowDimensions.md
- package.json
- src/index.ts
- src/rn/Dimensions.ts
- src/rn/__tests__/Dimensions.test.ts
- src/rn/__tests__/useWindowDimensions.test.tsx
- src/rn/useWindowDimensions.ts
- website/sidebars.json
- yarn.lock
> #321 dimensions

- docs/api/StatusBar.md
- src/index.ts
- src/rn/StatusBar.ts
- src/rn/__tests__/StatusBar.test.ts
- website/sidebars.json
> #389 status bar

- docs/api/Easing.md
- src/index.ts
- src/rn/Animated/Easing.ts
- src/rn/Animated/bezier.ts
- src/rn/__tests__/Easing.test.ts
- website/sidebars.json
> #392 easing

- src/rn/I18nManager.ts
- src/rn/__tests__/I18nManager.test.ts
> Implement I18nManager stub

- src/index.ts
- src/rn/NativeModules.ts
- src/rn/__tests__/NativeModules.test.ts
> Implement (React Native) NativeModules support

- src/index.ts
- src/rn/Animated/Animated.ts
- src/rn/Animated/index.ts
> Implement (RN) Animated module stub

- docs/api/render.md
- src/renderer.tsx
> Fix render function signature in the doc

- src/styleTransformers/__tests__/__snapshots__/transformShadowToEffect.test.ts.snap
- src/styleTransformers/__tests__/transformBlendProperties.test.ts
- src/styleTransformers/transformBlendProperties.ts
- src/styleTransformers/transformShadowToEffect.ts
- src/styleTransformers/transformTextStyleProperties.ts
Close [Issue Support multiple shadows](https://github.com/react-figma/react-figma/issues/292)
> feat: support multiple shadows props

- docs/ecosystem.md
> Typo fixed (line14)

- src/localStyles/useTextStyle.ts
> Add loading font check in useTextStyle

- .circleci/config.yml
- contributing.md
Hello, 
I've found some minor typos in the documentation, solved with this PR.
> Fix minor typos

- examples/auto-layout/manifest.json
- examples/basic-animation/manifest.json
- examples/basic-hmr/manifest.json
- examples/basic/manifest.json
- examples/component-variants/manifest.json
- examples/design-system/manifest.json
- examples/dynamic-layout/manifest.json
- examples/fetching/manifest.json
- examples/hyperlink/manifest.json
- examples/images/manifest.json
- examples/interactive/manifest.json
- examples/local-styles/manifest.json
- examples/mdx/manifest.json
- examples/styled-components/manifest.json
> Specify editorType in examples #494

- src/renderers/componentset.ts
> Fix Auto layout mixin is not applied to the components set

- package.json
- src/__tests__/__snapshots__/renderer.test.tsx.snap
- src/__tests__/renderer.test.tsx
- src/components/rectangle/__tests__/Rectangle.test.tsx
- src/components/rectangle/__tests__/__snapshots__/Rectangle.test.tsx.snap
- src/components/text/Text.tsx
- src/helpers/constants.ts
- src/helpers/removeKey.ts
- src/hooks/__tests__/__snapshots__/useInheritStyle.tsx.snap
- src/hooks/__tests__/useInheritStyle.tsx
- src/localStyles/__tests__/__snapshots__/useFillPaintStyle.test.tsx.snap
- src/localStyles/__tests__/__snapshots__/useStrokePaintStyle.test.tsx.snap
- src/localStyles/__tests__/__snapshots__/useStyleByKey.test.tsx.snap
- src/localStyles/__tests__/__snapshots__/useTextStyle.test.tsx.snap
- src/localStyles/__tests__/useFillPaintStyle.test.tsx
- src/localStyles/__tests__/useStrokePaintStyle.test.tsx
- src/localStyles/__tests__/useStyleByKey.test.tsx
- src/localStyles/__tests__/useTextStyle.test.tsx
- src/renderers/__tests__/text.test.ts
- src/renderers/text.ts
- src/rpc.ts
- src/yoga/__tests__/__snapshots__/integration.test.tsx.snap
- src/yoga/__tests__/integration.test.tsx
- yarn.lock
> Change default font

- docs/api/Svg.md
https://www.figma.com/plugin-docs/api/figma/#createnodefromsvg
> Fix createnodefromsvg link to figma docs.

- src/mixins/__tests__/baseNodeMixin.test.ts
- src/mixins/baseNodeMixin.ts
> Setting the "sharedPluginData" prop throws error
